sequenceDiagram
    autonumber
    participant C as CMD
    participant B as Browser
    participant A as Auth Service
    participant S as Spotify API
    C->>B: Open browser to spotify app access
    alt REJECT ACCESS
    B-->>B: Reject
    B-->>C: Error access code callback
    end
    alt ACCEPT ACCESS
        B-->>B: Accept
        B-->>C: Access code callback
        C->>A: Send access code to request token
        A->>S: Request access and refresh token 
        alt ERROR REQUESTING ACCESS / REFRESH TOKEN
            S-->>A: Unable to request access and refresh token
            A-->>C: Unable to request access and refresh token
        end
        alt ACCESS/REFRESH TOKEN
            S-->>A: access/refresh token response 
            A->>C: store locally access/refresh token 
        end
    end
